
name: Build HeartMonitor

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Geode Android mod
        id: build
        uses: geode-sdk/build-geode-mod@main
        with:
          target: Android64
          sdk: given

      - name: Upload compiled mod
        uses: actions/upload-artifact@v4
        with:
          name: HeartMonitor-Android
          path: ${{ steps.build.outputs.build-output }}/*.geode
          if-no-files-found: error
          
